pipeline {
    agent any 

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'c6ca6e86-bab1-4ffa-ad4a-9f8259dcb7c6',
                url: 'https://github.com/IMASHM/Jenkins-Zero-To-Hero.git',  // Repo URL
                branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo 'Building Docker Image'
                    docker build -t ashishm9/cicd-e2e:${BUILD_NUMBER} .  // DockerHub username
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh '''
                    echo 'Pushing Docker Image to DockerHub'
                    docker push ashishm9/cicd-e2e:${BUILD_NUMBER}  // DockerHub username
                    '''
                }
            }
        }

        stage('Checkout K8S Manifests') {
            steps {
                git credentialsId: 'c6ca6e86-bab1-4ffa-ad4a-9f8259dcb7c6', 
                url: 'https://github.com/IMASHM/Jenkins-Zero-To-Hero.git',  // Repo URL (same for your case)
                branch: 'main'
            }
        }

        stage('Update K8S Manifest & Push to Repo') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'c6ca6e86-bab1-4ffa-ad4a-9f8259dcb7c6', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy/deploy.yaml  // Assuming your Kubernetes manifest is under deploy/deploy.yaml
                        sed -i "s/32/${BUILD_NUMBER}/g" deploy/deploy.yaml
                        cat deploy/deploy.yaml
                        git add deploy/deploy.yaml
                        git commit -m 'Updated the deploy.yaml with build number | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/IMASHM/Jenkins-Zero-To-Hero.git HEAD:main  // Repo URL (same for your case)
                        '''
                    }
                }
            }
        }
    }
}
